### ISSUE TITLE
查询环境变量错误 【404】 删除comment，id=【11224924】

### ISSUE THREAD

**Issue by wood-sheep** [ma-xin/JDCKWebApp#1]
大佬，我根据https://www.kejiwanjia.com/jiaocheng/89722.html/comment-page-7#comment教程打包了app, 在gitee上存在评论，但我在青龙面板上跑 connectGitee.py时，日志打印  查询环境变量错误 【404】 删除comment，id=【11224924】 ，该咋办呢？

**Comment by ma-xin** [comment]
应该是青龙版本导致的兼容性问题， 你先试试用[giteeCK-a3.py](https://github.com/ma-xin/JDCKWebApp/blob/master/temp/giteeCK-a3.py)，这个是做过兼容处理的，如果还出现问题，你把青龙的版本号和错误日志发出来

**Comment by wood-sheep** [comment]
> 应该是青龙版本导致的兼容性问题， 你先试试用[giteeCK-a3.py](https://github.com/ma-xin/JDCKWebApp/blob/master/temp/giteeCK-a3.py)，这个是做过兼容处理的，如果还出现问题，你把青龙的版本号和错误日志发出来
感谢大佬，解决了：-）
